site_name: lab6demo

site_url: https://crose26.github.io/lab6demo

repo_url: https://github.com/crose26/lab6demo

theme:
    palette:
        scheme: preference
    name: material
    icon:
        repo: fontawesome/brands/github
    features:
        - navigation.instant
        - search.highlight
        # - navigation.expand
        # - navigation.tabs
    custom_dir: "docs/overrides"

plugins:
    - search
    - mkdocstrings
    - git-revision-date
    - mkdocs-jupyter:
          include_source: True
          # execute: True
          
markdown_extensions:
    - attr_list
    - pymdownx.superfences
    - pymdownx.highlight:
          linenums: true
    - toc:
          permalink: true

# google_analytics:
#     - UA-XXXXXXXXX-X
#     - auto

nav:
    - Home: index.md
    - Installation: installation.md
    - Usage: usage.md
    - Contributing: contributing.md
    - FAQ: faq.md
    - Report Issues: https://github.com/crose26/lab6demo/issues
    - API Reference:
          - lab6demo module: lab6demo.md
    - Notebooks:
            -folium intro: notebooks\folium_intro.ipynb
            -example notebook: notebooks\Example Notebook.ipynb
            -Untitled: notebooks\Untitled.ipynb